### PR TITLE
Parser void

### PR DESCRIPTION
**Pull request by nutka7**
Adressed Adrian's issues regarding parser. 
It interprets escape sequences like in Javascript - it differs slightly from C's way, but only in code point handling.

### CODE REVIEW

**Comment by chaser92** [comment]
But build fails... did you do a rebase to current master?

**Comment by nutka7** [comment]
Yup, notice that in current master build fails.

**Comment by chaser92** [comment]
ok

2015-04-26 2:05 GMT+02:00 nutka7 notifications@github.com:

> Yup, notice that in current master build fails.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bdfhjk/VIPER/pull/53#issuecomment-96297734.

## 

Pozdrawiam,
Mariusz Kierski

**Comment by nutka7** [comment]
Final version. There is no support for specifying characters by code points, but otherwise it is 100% compatible with C's string literals and moreover only 100% correct char/string literals are parsed.

**Pull request merged**
